baseURL = 'https://rodafr.github.io/'
languageCode = 'en-us'
title = 'rwdf blogs'
theme = 'poison'

[author]
    name = "rwdf"
    location = "Trondheim, Norway"

[params]
    brand = "RWDF"
    brand_image = "/rwdf.png"
    description = "blog"
    dark_mode = "true"
    front_page_content = ["posts"]

menu =  [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
]

mastodon_url = "https://fribygda.no/@rwdf"

[taxonomies]
  tags = 'tags'
  series = 'series'
